---

- name: create directory
  become: yes
  file: 
    path: ~/backend
    state: directory
    owner: ubuntu
    group: ubuntu

# - name: deploy backend
#   unarchive:
#     src: ~/project/artifact.tar.gz
#     dest: ~/backend
#     owner: ubuntu
#     group: ubuntu

- name: Install Node 
  shell: |
    cd /home/ubuntu/backend
    npm install
    
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- start

