---

- name: create directory
  file: 
    path: .circleci/backend
    state: directory

- name: copying files
  become: true
  copy:
    src: artifact.tar.gz
    dest: .circleci/backend

- name: unzip artifact
  become: yes
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start app
  become: true
  shell: |
    cd .circleci/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env